#
###################################
# Site wide configuration
####################################
#
title: Chirag Sakhuja
email: 
description: A simple and awesome blog theme powered by jekyll.
url: https://chiragsakhuja.com
keywords: []

#
###################################
# Jekyll configuration
####################################
#
timezone:          US/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Chirag Sakhuja
  avatar: avatar.jpg
  job: "GPU Architect"
  bio: "Recently started my architecture/graphics career at NVIDIA"
  email: #email
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: chiragsakhuja #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: chirag-sakhuja-36331651 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
